<a href="https://colab.research.google.com/github/roshangeoroy/ITC-principles/blob/main/Linear%20Block%20Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Linear Block Code (LBC)
1. Create the k x n generator matrix, G of (n, k) LBC.
2. Generate all possible codewords by multiplying the message vector of length, k
with G.
3. Calculate the Hamming weight of all codewords and obtain the minimum distance,
dmin of the code.
4. Find its error correcting and detecting capability.


In [5]:
import numpy as np
k=int(input("Enter the no.of.information bits: "))
n=int(input("Enter the length of codeword: "))

Enter the no.of.information bits: 4
Enter the length of codeword: 7


In [13]:
#inputing Parity Matrix (Hamming)
P=input("Enter Parity Matrix of size {}x{} : ".format(k,n-k)).split(',')
P=np.array([int(x) for x in P])
P=P.reshape(k,n-k)
i_gen=list()
for i in range(k):
    i_gen.append(1)
I=np.diag(i_gen)
G=np.concatenate((P,I),axis=1)
print('Generator Matrix is :\n',G)

Enter Parity Matrix of size 4x3 : 1,1,0,0,1,1,1,1,1,1,0,1
Generator Matrix is :
 [[1 1 0 1 0 0 0]
 [0 1 1 0 1 0 0]
 [1 1 1 0 0 1 0]
 [1 0 1 0 0 0 1]]


In [33]:
C=np.empty(shape=(2**k,n))
X={}
for i in range(2**k):

    r=np.array([int(x) for x in np.binary_repr((i),width=k)])
    m=[int(x%2) for x in r@G]
    
    X[np.binary_repr((i),width=k)]=m
    C[i]=m

import pandas    as pd
y={'MessageWord':[key for key in X],'CodeWord':[X[i] for i in X]}
Y=pd.DataFrame(y)
Y


MessageWord               CodeWord
0         0000  [0, 0, 0, 0, 0, 0, 0]
1         0001  [1, 0, 1, 0, 0, 0, 1]
2         0010  [1, 1, 1, 0, 0, 1, 0]
3         0011  [0, 1, 0, 0, 0, 1, 1]
4         0100  [0, 1, 1, 0, 1, 0, 0]
5         0101  [1, 1, 0, 0, 1, 0, 1]
6         0110  [1, 0, 0, 0, 1, 1, 0]
7         0111  [0, 0, 1, 0, 1, 1, 1]
8         1000  [1, 1, 0, 1, 0, 0, 0]
9         1001  [0, 1, 1, 1, 0, 0, 1]
10        1010  [0, 0, 1, 1, 0, 1, 0]
11        1011  [1, 0, 0, 1, 0, 1, 1]
12        1100  [1, 0, 1, 1, 1, 0, 0]
13        1101  [0, 0, 0, 1, 1, 0, 1]
14        1110  [0, 1, 0, 1, 1, 1, 0]
15        1111  [1, 1, 1, 1, 1, 1, 1]

In [34]:
H=[]
H.append(0)
for i in range(len(C)-1):
    d=[int(x%2) for x in C[i]+C[i+1]]
    H.append(np.sum(d))
      
Hd=np.min(H[1:])
print('Minimum Distance:',Hd)

Minimum Distance: 3


In [35]:
s=Hd-1
print("Error detecting capacity: upto",s,"bits")
t=0.5*(Hd-1)
print("Error correcting capacity: upto",int(t),"bits")

Error detecting capacity: upto 2 bits
Error correcting capacity: upto 1 bits
