<a href="https://colab.research.google.com/github/roshangeoroy/ITC-principles/blob/main/Linear%20Block%20Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
k=int(input("Enter the no.of.information bits: "))
n=int(input("Enter the length of codeword: "))

Enter the no.of.information bits: 4
Enter the length of codeword: 7


In [2]:
P=input("Enter Parity Matrix of size {}x{} : ".format(k,n-k)).split(',')
P=np.array([int(x) for x in P])
P=P.reshape(k,n-k)
i_gen=list()
for i in range(k):
    i_gen.append(1)
I=np.diag(i_gen)
G=np.concatenate((I,P),axis=1)
print(G)

Enter Parity Matrix of size 4x3 : 1,0,1,1,1,1,1,1,0,0,1,1
[[1 0 0 0 1 0 1]
 [0 1 0 0 1 1 1]
 [0 0 1 0 1 1 0]
 [0 0 0 1 0 1 1]]


In [3]:
C=np.empty(shape=(2**k,n))
for i in range(2**k):
    r=np.array([int(x) for x in np.binary_repr((i),width=k)])
    m=[int(x%2) for x in r@G]
    C[i]=m
    
print(C)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 1.]
 [0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0. 1.]
 [0. 1. 0. 0. 1. 1. 1.]
 [0. 1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 1. 1. 0.]
 [1. 0. 1. 0. 0. 1. 1.]
 [1. 0. 1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0.]
 [1. 1. 0. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [4]:
H=[]
H.append(0)
for i in range(len(C)-1):
    d=[int(x%2) for x in C[i]+C[i+1]]
    H.append(np.sum(d))
      
Hd=np.min(H[1:])
print(Hd)

3


In [5]:
s=Hd-1
print("Error detecting capacity: upto",s,"bits")
t=0.5*(Hd-1)
print("Error correcting capacity: upto",int(t),"bits")

Error detecting capacity: upto 2 bits
Error correcting capacity: upto 1 bits
